<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>P4KToolsLibrary</AssemblyName>
        <RootNamespace>P4KToolsLibrary</RootNamespace>
        <AssemblyVersion>1.0</AssemblyVersion>
        <NeutralLanguage>en-CA</NeutralLanguage>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ZstdSharp.Port" Version="0.8.7" />
    </ItemGroup>

</Project>
